# Generated by Django 3.1.7 on 2021-03-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=5)),
                ('regions', models.JSONField()),
                ('working_hours', models.JSONField()),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('region', models.PositiveIntegerField()),
                ('delivery_hours', models.JSONField()),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.courier')),
            ],
        ),
    ]
