# Generated by Django 3.1.7 on 2021-04-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='assign_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_time', models.DateTimeField()),
                ('assign_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=5)),
                ('current_courier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_batch', to='delivery.courier')),
                ('past_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_batches', to='delivery.courier')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.batch'),
        ),
    ]
